export const doctorProfiles = [
  {
    slug: 'dr-aabid-amin-bhat-consultant-physician-karnal',
    name: 'Dr. Aabid Amin Bhat',
    designation: 'Consultant Physician',
    qualifications: 'MBBS, MD (General Medicine)',
    experience: '10+ years of clinical experience | Expertise in critical care',
    category: 'Internal Medicine and Critical Care',
    pageTitle: 'Consultant Physician and Critical Care Specialist in Karnal',
    headline: 'Comprehensive adult medical care with accurate diagnosis, timely treatment and critical care expertise.',
    image: '/doctors/dr-aabid-amin-bhat.png',
    imagePosition: 'center 18%',
    about: [
      'Dr. Aabid Amin Bhat is an experienced Consultant Physician with more than 10 years of clinical experience, with particular expertise in critical care and the management of complex medical conditions.',
      'He provides comprehensive, evidence-based medical care with a strong focus on accurate diagnosis, timely treatment and individualised patient care. His critical care experience supports the management of patients with serious and complicated medical conditions requiring close monitoring and specialised medical attention.',
      "Dr. Bhat follows a patient-centred approach, taking time to understand each patient's medical history, symptoms and healthcare needs before developing an appropriate treatment plan.",
    ],
    expertise: [
      'General and internal medicine',
      'Critical care and acute medical care',
      'Diabetes and hypertension management',
      'Fever and infectious diseases',
      'Respiratory and chest-related conditions',
      'Gastrointestinal disorders',
      'Thyroid and metabolic disorders',
      'Chronic medical condition management',
      'Acute and complex medical emergencies',
      'Comprehensive adult healthcare',
      'Acute management of poisoning and snake bite',
    ],
    servicesTitle: 'Common Conditions and Services',
    services: [
      'Adult OPD consultations for fever, weakness, chest symptoms, abdominal symptoms and chronic disease review',
      'Evaluation and management of diabetes, hypertension, thyroid disease and metabolic disorders',
      'Assessment and stabilization of acute medical emergencies and critically ill patients',
      'Long-term follow-up and treatment planning for chronic medical illnesses',
    ],
    careMessage: [
      "Compassionate care, accurate diagnosis and timely treatment are central to Dr. Bhat's clinical approach.",
      'He believes effective healthcare goes beyond treating a disease. He focuses on listening to patients, explaining treatment options clearly and providing personalised medical care.',
    ],
    cta: 'Consult Dr. Aabid Amin Bhat for internal medicine, adult healthcare, chronic disease management and critical care-related medical concerns.',
    metaTitle: 'Dr. Aabid Amin Bhat | Consultant Physician in Karnal | Gajraj Hospital',
    metaDescription: 'Consult Dr. Aabid Amin Bhat, MBBS, MD General Medicine, Consultant Physician with 10+ years of clinical experience and expertise in critical care at Gajraj Hospital, Karnal.',
    keywords: ['Dr. Aabid Amin Bhat', 'Physician in Karnal', 'Internal Medicine Doctor in Karnal', 'Critical Care Doctor in Karnal', 'Gajraj Hospital Karnal'],
  },
  {
    slug: 'dr-parveen-garg-general-laparoscopic-surgeon-karnal',
    name: 'Dr. Parveen Garg',
    designation: 'Senior Consultant - General and Laparoscopic Surgery',
    qualifications: 'MBBS, MS (General Surgery)',
    experience: '38+ years of experience in general and laparoscopic surgery',
    category: 'General Surgery and Laparoscopic Surgery',
    pageTitle: 'General and Laparoscopic Surgeon in Karnal',
    headline: '38+ years of surgical experience with patient-focused general and laparoscopic surgical care.',
    image: '/doctors/dr-parveen-garg.png',
    imagePosition: 'center 34%',
    about: [
      'Dr. Parveen Garg is an experienced General and Laparoscopic Surgeon at Gajraj Hospital, Karnal, with more than 38 years of experience in surgical care.',
      'He provides comprehensive surgical evaluation and treatment for a wide range of conditions. His approach focuses on accurate diagnosis, appropriate surgical planning, patient safety and personalised post-operative care.',
      'Over a long clinical career, Dr. Garg has developed extensive experience in managing routine as well as complex surgical conditions.',
    ],
    expertise: [
      'General surgery',
      'Laparoscopic surgery',
      'Gallbladder and gallstone surgery',
      'Appendix surgery',
      'Hernia surgery',
      'Intestinal and abdominal surgery',
      'Management of surgical conditions',
      'Minor and major surgical procedures',
      'Pre-operative and post-operative care',
      'Emergency surgical evaluation and trauma-related surgical care',
    ],
    servicesTitle: 'Conditions Commonly Managed',
    services: [
      'Gallstones and gallbladder-related problems',
      'Appendicitis',
      'Hernia',
      'Persistent or recurrent abdominal pain requiring surgical evaluation',
      'Certain intestinal conditions',
      'Surgical wounds or infections',
      'Lumps or growths requiring surgical removal',
      'Critically injured patients requiring urgent surgical evaluation',
      'Emergency operations for serious injuries caused by accidents, falls or major trauma',
    ],
    detailSections: [
      {
        title: 'Laparoscopic Surgery',
        paragraphs: [
          'Laparoscopic surgery, also known as minimally invasive surgery, uses small incisions and specialised instruments to perform selected surgical procedures.',
          "Dr. Garg's surgical practice includes laparoscopic evaluation and treatment of selected abdominal and general surgical conditions.",
        ],
      },
    ],
    careMessage: [
      "Experience, precision and compassionate care guide Dr. Garg's surgical practice.",
      'He believes good surgical care begins with thorough evaluation and clear communication. His approach extends from consultation and diagnosis to surgery, recovery and post-operative follow-up.',
    ],
    cta: 'Consult Dr. Parveen Garg for general surgery, laparoscopic surgery, gallbladder surgery, appendix surgery, hernia surgery and surgical evaluation of abdominal complaints.',
    metaTitle: 'Dr. Parveen Garg | General and Laparoscopic Surgeon in Karnal | Gajraj Hospital',
    metaDescription: 'Consult Dr. Parveen Garg, MBBS, MS General Surgery, Senior Consultant General and Laparoscopic Surgeon at Gajraj Hospital, Karnal, with 38+ years of surgical experience.',
    keywords: ['Dr. Parveen Garg', 'General Surgeon in Karnal', 'Laparoscopic Surgeon in Karnal', 'Hernia Surgeon in Karnal', 'Gallbladder Surgeon in Karnal', 'Appendix Surgeon in Karnal', 'Gajraj Hospital Karnal'],
  },
  {
    slug: 'dr-mir-mehfooza-gani-anaesthesiologist-intensivist-karnal',
    name: 'Dr. Mir Mehfooza Gani',
    designation: 'Consultant Anaesthesiologist and Intensivist | Critical Care Specialist',
    qualifications: 'Gold Medalist | MBBS, MD (Anaesthesiology and Critical Care Medicine)',
    experience: '10+ years of clinical experience in anaesthesia and critical care',
    category: 'Anaesthesia, Intensive Care and Critical Care',
    pageTitle: 'Anaesthesiologist and Critical Care Specialist in Karnal',
    headline: 'Advanced anaesthesia and critical care with a patient-first approach.',
    image: '/doctors/dr-mir-mehfooza-gani.png',
    imagePosition: 'center 18%',
    about: [
      'Dr. Mir Mehfooza Gani is a Gold Medalist and experienced Consultant Anaesthesiologist and Intensivist at Gajraj Hospital, Karnal, with more than 10 years of clinical experience in anaesthesia, critical care and intensive medical support.',
      'She provides comprehensive perioperative care, ensuring patient safety before, during and after surgical procedures. Her intensive care experience supports the management of critically ill and high-risk patients requiring close monitoring, timely intervention and multidisciplinary care.',
      'Her clinical work includes critical care medicine, respiratory emergencies, cardiac emergencies, neurological and neurosurgical critical care, complex post-operative patients, organ support, mechanical ventilation and haemodynamic monitoring.',
    ],
    expertise: [
      'General anaesthesia',
      'Regional and local anaesthesia',
      'Perioperative and surgical care',
      'Intensive care and critical care',
      'Management of critically ill patients',
      'Emergency and acute care',
      'Pre-operative patient assessment',
      'Post-operative monitoring and care',
      'Pain management',
      'Airway management',
      'Mechanical ventilation and respiratory failure',
      'Haemodynamic monitoring and support',
      'High-risk respiratory and pulmonary cases',
      'Cardiac emergencies and critically ill cardiac patients',
      'Neurological and neurosurgical critical care',
      'High-risk and complex postoperative care',
      'Emergency and life-support management',
      'Multidisciplinary management of critically ill patients',
    ],
    servicesTitle: 'Common Conditions and Services',
    services: [
      'Anaesthesia planning and monitoring for surgical procedures',
      'Pre-operative assessment of high-risk patients',
      'ICU management of respiratory failure, shock, sepsis and complex medical/surgical illness',
      'Mechanical ventilation and organ support in critically ill patients',
      'Post-operative intensive monitoring and recovery support',
    ],
    detailSections: [
      {
        title: 'Expertise in Anaesthesia',
        paragraphs: [
          'Anaesthesia plays an important role in ensuring patient comfort, safety and stability during surgical procedures.',
          "Dr. Gani provides anaesthesia care tailored to the patient's medical condition, type of surgery and individual requirements, with careful monitoring throughout the perioperative period.",
        ],
      },
      {
        title: 'Critical Care and Intensive Care',
        paragraphs: [
          'As an intensivist, Dr. Gani is involved in the management of patients requiring continuous monitoring and intensive medical care.',
          'Her practice includes supporting vital organ function and coordinating care with specialists and the multidisciplinary ICU team.',
        ],
      },
    ],
    careMessage: [
      "Careful assessment, precise anaesthesia and dedicated critical care define Dr. Gani's patient safety approach.",
      'From pre-operative assessment through anaesthesia, ICU care and recovery, her focus remains on individualised care, careful monitoring and safe recovery.',
    ],
    cta: 'Consult Dr. Mir Mehfooza Gani for anaesthesia care, critical care, intensive care and management of critically ill or high-risk patients.',
    metaTitle: 'Dr. Mir Mehfooza Gani | Anaesthesiologist and Intensivist in Karnal | Gajraj Hospital',
    metaDescription: 'Consult Dr. Mir Mehfooza Gani, Gold Medalist, MBBS, MD Anaesthesiology and Critical Care Medicine, Anaesthesiologist and Intensivist with 10+ years of experience at Gajraj Hospital, Karnal.',
    keywords: ['Dr. Mir Mehfooza Gani', 'Anaesthesiologist in Karnal', 'Intensivist in Karnal', 'Critical Care Doctor in Karnal', 'ICU Doctor in Karnal', 'Anaesthesia Specialist in Karnal'],
  },
  {
    slug: 'dr-shruti-sharma-obstetrician-gynaecologist-karnal',
    name: 'Dr. Shruti Sharma',
    designation: 'Consultant Obstetrician and Gynaecologist',
    qualifications: 'MBBS, DNB (Obstetrics and Gynaecology), PGDS - Sonography and Infertility Specialities',
    experience: '8+ years of clinical experience',
    category: 'Obstetrics, Gynaecology, Sonography and Infertility Evaluation',
    pageTitle: 'Obstetrician and Gynaecologist in Karnal',
    headline: "Complete women's healthcare with compassionate care and trusted guidance.",
    image: '/doctors/dr-shruti-sharma.png',
    imagePosition: 'center 20%',
    about: [
      "Dr. Shruti Sharma is an experienced Consultant Obstetrician and Gynaecologist at Gajraj Hospital, Karnal, with more than 8 years of clinical experience in women's healthcare.",
      "She provides comprehensive care across different stages of a woman's life, including gynaecological health, pregnancy care, antenatal care, reproductive health, sonography and infertility-related evaluation.",
      'With additional training in sonography and infertility specialities, Dr. Sharma combines clinical assessment with appropriate diagnostic evaluation and personalised treatment planning.',
    ],
    expertise: [
      'Antenatal and pregnancy care',
      'High-risk pregnancy evaluation',
      'Routine pregnancy monitoring',
      'Pre- and postnatal care',
      'Pregnancy-related medical concerns',
      'Menstrual disorders',
      'PCOS/PCOD management',
      'Abnormal uterine bleeding',
      'Vaginal and pelvic health concerns',
      'Gynaecological infections',
      'Menopausal health',
      "Women's preventive healthcare",
      'Obstetric sonography',
      'Pregnancy ultrasound evaluation',
      'Gynaecological and pelvic ultrasound',
      'Infertility evaluation',
      'Preconception counselling',
      'Fertility assessment',
      'PCOS-related fertility concerns',
      'Reproductive health counselling',
    ],
    servicesTitle: 'Patient Needs Covered',
    services: [
      'Pregnancy and antenatal follow-up',
      'Evaluation of menstrual problems, PCOS, abnormal bleeding and pelvic concerns',
      'Sonography-based assessment when clinically indicated',
      'Initial infertility work-up and fertility counselling',
      'Preconception and reproductive health counselling',
      "Preventive women's healthcare and menopausal health support",
    ],
    detailSections: [
      {
        title: 'Pregnancy and Maternity Care',
        paragraphs: [
          'Pregnancy requires regular medical supervision and appropriate monitoring. Dr. Sharma provides antenatal care throughout pregnancy, helping expectant mothers understand changing health needs and follow the right investigations and follow-up schedule.',
        ],
      },
      {
        title: 'Infertility Care',
        paragraphs: [
          'For couples experiencing difficulty conceiving, timely evaluation can help identify possible contributing factors. Dr. Sharma provides initial infertility assessment, fertility evaluation and preconception counselling, with treatment recommendations based on individual needs.',
        ],
      },
    ],
    careMessage: [
      'Dr. Shruti Sharma believes in creating a comfortable and supportive environment where women can openly discuss their health concerns.',
      "Her goal is to provide respectful, personalised and evidence-based women's healthcare while keeping patients informed about diagnosis and treatment options.",
    ],
    cta: 'Consult Dr. Shruti Sharma for pregnancy care, gynaecology concerns, sonography-based evaluation, PCOS/PCOD, abnormal bleeding and infertility assessment.',
    metaTitle: 'Dr. Shruti Sharma | Obstetrician and Gynaecologist in Karnal | Gajraj Hospital',
    metaDescription: 'Consult Dr. Shruti Sharma, MBBS, DNB Obstetrics and Gynaecology, PGDS Sonography and Infertility Specialities, for pregnancy care, gynaecology and infertility evaluation at Gajraj Hospital, Karnal.',
    keywords: ['Dr. Shruti Sharma', 'Gynaecologist in Karnal', 'Obstetrician in Karnal', 'Pregnancy Doctor in Karnal', 'Infertility Evaluation in Karnal', 'Gajraj Hospital Karnal'],
  },
  {
    slug: 'dr-akshay-lamba-orthopaedic-surgeon-karnal',
    name: 'Dr. Akshay Lamba',
    designation: 'Consultant Orthopaedic Surgeon',
    qualifications: 'MBBS, MS (Orthopaedics) | PGI Rohtak',
    experience: 'Comprehensive orthopaedic care and surgical services',
    category: 'Orthopaedics, Joint Replacement, Trauma and Sports Injury Surgery',
    pageTitle: 'Orthopaedic Surgeon in Karnal',
    headline: 'Comprehensive orthopaedic evaluation and surgical care for bones, joints, trauma and sports injuries.',
    image: '/doctors/dr-akshay-lamba.png',
    imagePosition: 'center 18%',
    about: [
      'Dr. Akshay Lamba is a Consultant Orthopaedic Surgeon providing comprehensive evaluation and surgical management of conditions affecting the bones, joints, muscles, ligaments, tendons and musculoskeletal system.',
      'His clinical and surgical practice includes joint replacement, arthroscopic surgery, fracture and trauma management, sports injuries, hand and upper-limb conditions, foot and ankle disorders, paediatric orthopaedics, reconstructive surgery and deformity correction.',
      'Each patient is assessed individually, with treatment planned according to the clinical condition, diagnostic findings, functional requirements and overall health.',
    ],
    expertise: [
      'Joint replacement surgery including knee, hip, shoulder, elbow and ankle replacement',
      'Arthroscopic and minimally invasive surgery including knee, shoulder, ankle, hip and elbow arthroscopy',
      'ACL, PCL, meniscus, rotator cuff and ligament reconstruction procedures',
      'Fracture and orthopaedic trauma surgery including ORIF, CRIF, plating, screws, nailing and external fixation',
      'Pelvic, acetabular, hip, femur, tibia, fibula, ankle, wrist, hand, clavicle and shoulder fracture surgery',
      'Sports injury surgery and tendon repair',
      'Hand, wrist, shoulder, elbow and upper-limb surgery',
      'Foot and ankle surgery including Achilles tendon repair, ankle ligament reconstruction, bunion correction and flat foot reconstruction',
      'Paediatric orthopaedics including clubfoot treatment, paediatric fracture care, congenital deformity correction and developmental hip dysplasia management',
      'Deformity and reconstructive orthopaedic surgery including limb deformity correction, limb lengthening, bone grafting, non-union and malunion surgery',
      'Joint injection procedures, bone tumour surgery, infection or septic arthritis surgery and orthopaedic trauma reconstruction',
    ],
    servicesTitle: 'Areas of Care',
    services: [
      'Joint replacement',
      'Arthroscopy',
      'Sports injuries',
      'Fracture and trauma',
      'Hand and upper limb',
      'Foot and ankle',
      'Paediatric orthopaedics',
      'Deformity correction',
      'Reconstructive surgery',
    ],
    detailSections: [
      {
        title: 'Comprehensive Orthopaedic Care',
        paragraphs: [
          'From fracture and trauma care to joint replacement and arthroscopic procedures, Dr. Lamba provides surgical management for a broad range of orthopaedic and musculoskeletal conditions.',
          'Treatment is planned on an individual basis after detailed clinical evaluation and appropriate diagnostic assessment. Where suitable, both surgical and non-surgical treatment options may be considered to help patients improve mobility, function and quality of life.',
        ],
      },
    ],
    careMessage: [
      "Dr. Lamba's approach focuses on individual assessment, functional needs, diagnostic findings and safe surgical planning.",
      'The goal is to help patients regain mobility and quality of life through appropriate orthopaedic evaluation and treatment.',
    ],
    cta: 'Consult Dr. Akshay Lamba for comprehensive evaluation and management of orthopaedic conditions, joint pain, trauma, fractures, sports injuries and joint replacement needs.',
    metaTitle: 'Dr. Akshay Lamba | Orthopaedic Surgeon in Karnal | Gajraj Hospital',
    metaDescription: 'Consult Dr. Akshay Lamba, MBBS, MS Orthopaedics, PGI Rohtak, Consultant Orthopaedic Surgeon for joint replacement, arthroscopy, fractures, sports injuries and orthopaedic trauma at Gajraj Hospital, Karnal.',
    keywords: ['Dr. Akshay Lamba', 'Orthopaedic Surgeon in Karnal', 'Joint Replacement Surgeon in Karnal', 'Fracture Doctor in Karnal', 'Sports Injury Doctor in Karnal', 'Gajraj Hospital Karnal'],
  },
  {
    slug: 'dr-himanshu-parashar-interventional-cardiologist-karnal',
    name: 'Dr. Himanshu Parashar',
    designation: 'Senior Interventional Cardiologist',
    qualifications: 'MBBS, MD, DNB (Cardiology), MCSI | International Associate Member of American College of Cardiology',
    experience: '10+ years of experience in cardiology and comprehensive heart care',
    category: 'Cardiology and Interventional Cardiology',
    pageTitle: 'Interventional Cardiologist in Karnal',
    headline: 'Comprehensive heart care with timely diagnosis, evidence-based treatment and interventional cardiology expertise.',
    image: '/doctors/dr-himanshu-parashar.png',
    imagePosition: 'center 20%',
    about: [
      'Dr. Himanshu Parashar is a Senior Interventional Cardiologist with more than 10 years of experience in cardiology and comprehensive heart care. He holds advanced qualifications including MBBS, MD, DNB (Cardiology) and MCSI.',
      'His clinical focus includes interventional cardiology, coronary heart disease and comprehensive evaluation and management of cardiovascular conditions.',
      'Dr. Parashar believes effective cardiac care begins with timely diagnosis, sound clinical judgment and an individualised approach to every patient. He considers symptoms, medical history, risk factors, investigations and overall health before developing an appropriate treatment plan.',
    ],
    expertise: [
      'Interventional cardiology',
      'Coronary artery disease',
      'Heart attack and acute cardiac care',
      'Angina and chest pain evaluation',
      'Hypertension management',
      'Heart failure management',
      'Cardiac arrhythmias',
      'Cardiovascular risk management',
      'Preventive cardiology',
      'Patient counselling for heart disease and treatment options',
    ],
    servicesTitle: 'Common Conditions and Services',
    services: [
      'Evaluation of chest pain, breathlessness, palpitations and suspected cardiac symptoms',
      'Management of coronary artery disease and heart attack risk',
      'Assessment and treatment planning for hypertension, heart failure and arrhythmias',
      'Preventive cardiology and cardiovascular risk reduction',
      'Interventional cardiology consultation and procedure planning when indicated',
    ],
    detailSections: [
      {
        title: 'Professional Memberships',
        paragraphs: [
          'MCSI refers to membership of the Cardiological Society of India. Dr. Parashar is also listed as an International Associate Member of the American College of Cardiology.',
        ],
      },
    ],
    careMessage: [
      'Dr. Parashar is committed to advanced, evidence-based cardiac care while maintaining a compassionate and patient-centred approach.',
      'His professional philosophy is centred on precision in diagnosis, timely intervention, continuity of care and putting the patient first.',
    ],
    cta: 'Consult Dr. Himanshu Parashar for chest pain, heart attack risk, coronary artery disease, hypertension, heart failure, arrhythmias and interventional cardiology consultation.',
    metaTitle: 'Dr. Himanshu Parashar | Interventional Cardiologist in Karnal | Gajraj Hospital',
    metaDescription: 'Consult Dr. Himanshu Parashar, MBBS, MD, DNB Cardiology, MCSI, Senior Interventional Cardiologist with 10+ years of experience in heart care at Gajraj Hospital, Karnal.',
    keywords: ['Dr. Himanshu Parashar', 'Cardiologist in Karnal', 'Interventional Cardiologist in Karnal', 'Heart Specialist in Karnal', 'Chest Pain Doctor in Karnal', 'Gajraj Hospital Karnal'],
  },
  {
    slug: 'dr-girish-sharma-plastic-surgeon-karnal',
    name: 'Dr. Girish Sharma',
    designation: 'Burn, Cosmetic and Reconstructive Plastic Surgeon',
    qualifications: 'MBBS, MS (General Surgery), MCh (Plastic Surgery)',
    experience: 'Plastic surgery, burn care, wound care, reconstructive and aesthetic procedures',
    category: 'Plastic Surgery, Burn Care, Cosmetic and Reconstructive Surgery',
    pageTitle: 'Plastic, Burn and Reconstructive Surgeon in Karnal',
    headline: 'Individualised burn, reconstructive and aesthetic care with attention to function, healing and appearance.',
    image: '/doctors/dr-girish-sharma.png',
    imagePosition: 'center 17%',
    about: [
      'Dr. Girish Sharma is a Burn, Cosmetic and Reconstructive Plastic Surgeon providing comprehensive care for burn injuries, complex wounds, scars, reconstructive needs and aesthetic concerns.',
      "With qualifications in General Surgery and Plastic Surgery, he offers individualized treatment plans based on the patient's medical condition, functional requirements and aesthetic goals.",
      'His clinical areas include burn management, complex wound care, scar management and revision, reconstructive surgery, body contouring, aesthetic breast surgery, hair restoration and non-surgical aesthetic procedures.',
    ],
    expertise: [
      'Acute burn management, burn contracture management, burn scar management, burn scar revision and post-burn rehabilitation',
      'Complex wound and reconstructive care for non-healing wounds, diabetic wounds, burn wounds, accidental wounds and traumatic wounds',
      'Leg defects with exposed bone, vascular injuries, nerve injuries and tendon injuries',
      'Scar management and revision for post-burn scars, hypertrophic scars, keloids, scar revision and tattoo removal',
      'Liposuction and body contouring including abdominal liposuction, full-body 360-degree liposuction, gynecomastia correction, butt lift and fat grafting',
      'Aesthetic breast surgery including breast augmentation, breast reduction, mastopexy and breast fat grafting',
      'Non-surgical aesthetic and hair restoration procedures including Botox, dermal fillers, thread lift, hair transplant and PRP hair treatment',
    ],
    servicesTitle: 'Conditions and Concerns Treated',
    services: [
      'Burn injuries and post-burn contractures',
      'Burn scars, keloids and hypertrophic scars',
      'Chronic and non-healing wounds',
      'Diabetic wounds',
      'Traumatic soft-tissue injuries',
      'Vascular, nerve and tendon injuries',
      'Gynecomastia',
      'Localized excess fat',
      'Breast shape and size concerns',
      'Hair loss',
      'Aesthetic and age-related concerns',
    ],
    detailSections: [
      {
        title: 'Why Consult Dr. Girish Sharma',
        paragraphs: [
          'Patients may consult Dr. Sharma for specialised plastic surgery qualification, expertise across burn, reconstructive and aesthetic procedures, individualised treatment planning and access to a multidisciplinary hospital environment at Gajraj Hospital, Karnal.',
        ],
      },
    ],
    faqs: [
      { question: 'What does a plastic surgeon treat?', answer: 'Plastic surgeons manage reconstruction, burns, wounds, scars, soft-tissue defects and aesthetic concerns. Treatment may be surgical or non-surgical depending on need.' },
      { question: 'When should a plastic surgeon be consulted after a burn?', answer: 'Consultation may be needed during the acute phase or later if scars, contractures, restricted movement or other post-burn problems develop.' },
      { question: 'Can burn scars be treated?', answer: 'Yes. Depending on type, location, size and maturity, options may include scar management, non-surgical treatments or scar revision procedures.' },
      { question: 'What is liposuction?', answer: 'Liposuction removes localized fat deposits to improve contour. It is not generally a substitute for weight-loss treatment.' },
      { question: 'Is every patient suitable for cosmetic or reconstructive surgery?', answer: 'No. Suitability depends on overall health, medical history, expectations, condition and procedure. Clinical assessment is necessary before treatment.' },
    ],
    careMessage: [
      "Plastic surgery can involve both functional and aesthetic considerations. Dr. Sharma begins with a detailed assessment of the patient's concerns and medical requirements.",
      'Treatment options are discussed so patients understand expected benefits, limitations, recovery considerations and potential risks before proceeding.',
    ],
    cta: 'Consult Dr. Girish Sharma for burn injury care, complex wounds, scar revision, reconstructive concerns, aesthetic procedures and hair restoration-related consultation.',
    metaTitle: 'Dr. Girish Sharma | Plastic, Burn and Reconstructive Surgeon | Gajraj Hospital Karnal',
    metaDescription: 'Consult Dr. Girish Sharma, MBBS, MS General Surgery, MCh Plastic Surgery, Burn, Cosmetic and Reconstructive Plastic Surgeon at Gajraj Hospital, Karnal.',
    keywords: ['Dr. Girish Sharma', 'Plastic Surgeon in Karnal', 'Burn Surgeon in Karnal', 'Cosmetic Plastic Surgeon in Karnal', 'Reconstructive Plastic Surgeon in Karnal', 'Burn Treatment in Karnal', 'Scar Revision', 'Gynecomastia Treatment', 'Liposuction in Karnal', 'Hair Transplant in Karnal'],
  },
]

export const doctorCategories = [...new Set(doctorProfiles.map((doctor) => doctor.category))]

export function getDoctorBySlug(slug) {
  return doctorProfiles.find((doctor) => doctor.slug === slug)
}
